
ZOHO_CLIENT_ID = "1000.G4X7HO0B5N0IBCYRXVTLVPEB318L4X"
ZOHO_CLIENT_SECRET = "2071f02628cd75250754af00b4e8913e0f3224143e"
ZOHO_ACCESS_TOKEN = "1000.988c84e0a499ab2eff25fe877cffe8ad.7a70782933a93411e5e62aaf817f8bb5"
ZOHO_REFRESH_TOKEN = "1000.94d369a683244f0d5f0615d503102652.f3e9815d2e54bc823608796a7a90e72e"
ZOHO_ORG_ID = "60058089972"
ZOHO_API_DOMAIN = "https://desk.zoho.in"
